version: '3.8'

services:
  whatsapp-api:
    image: wppconnect/server-cli:latest
    container_name: whatsapp-api
    restart: always
    ports:
      - "21465:21465"
    environment:
      - PORT=21465
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - ./wppconnect-data:/usr/src/app/session
    command:
      - --secretKey=${SECRET_KEY}
      - --startAllSession
      - --webhook-url=http://webhook:5000/webhook/whatsapp
      - --webhook-autoDownload
      - --webhook-readMessage
    networks:
      - app_network
    tty: true

  webhook:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5000 webhook:app --log-level debug --access-logfile -
    container_name: webhook
    ports:
      - "5000:5000"
    depends_on:
      - whatsapp-api
    env_file:
      - .env
    networks:
      - app_network

networks:
  app_network:
    driver: bridge